<?xml version="1.0" encoding="utf-8"?><Database Name="UGentMedicalStudentRostering" Class="UGentMSRDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=UGentMedicalStudentRostering;Integrated Security=True" SettingsObjectName="DataLayer.Properties.Settings" SettingsPropertyName="UGentMedicalStudentRosteringConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MSRAbilityIDInfo" Member="MSRAbilityIDInfos">
    <Type Name="MSRAbilityIDInfo">
      <Column Name="AbilityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisciplineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HospitalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ifAble" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StudentAbilityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRWardInfo" Member="MSRWardInfos">
    <Type Name="MSRWardInfo">
      <Column Name="WardID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WardName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRAvailablityInfo" Member="MSRAvailablityInfos">
    <Type Name="MSRAvailablityInfo">
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentAvID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MonthID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ifAvailable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AvailbilityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MSRDiscDurationPrInfo" Member="MSRDiscDurationPrInfos">
    <Type Name="MSRDiscDurationPrInfo">
      <Column Name="DiscDurationPrID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DiscplineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrainginProgramID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRDiscGroupInfo" Member="MSRDiscGroupInfos">
    <Type Name="MSRDiscGroupInfo">
      <Column Name="DiscGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DiscGroupName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRDisciplineInfo" Member="MSRDisciplineInfos">
    <Type Name="MSRDisciplineInfo">
      <Column Name="DisciplineID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisciplineName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiscDurationPrID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisciplinePrecedenceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisciplineOverseaReqID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseCredit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRDisciplineListInfo" Member="MSRDisciplineListInfos">
    <Type Name="MSRDisciplineListInfo">
      <Column Name="DiscListID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ListID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisciplineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRDisciplinePrecedenceInfo" Member="MSRDisciplinePrecedenceInfos">
    <Type Name="MSRDisciplinePrecedenceInfo">
      <Column Name="DisciplinePrecedenceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisciplineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrecedenceDiscID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRHospitalInfo" Member="MSRHospitalInfos">
    <Type Name="MSRHospitalInfo">
      <Column Name="HospitalID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HospitalName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HospitalRegionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HospitalWardDemandID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRHospitalWardDemandInfo" Member="MSRHospitalWardDemandInfos">
    <Type Name="MSRHospitalWardDemandInfo">
      <Column Name="WardID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HospitalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MonthID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmrDemand" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResDemand" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxDemand" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinDemand" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WardDemandID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HospitalDemandID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRListInfo" Member="MSRListInfos">
    <Type Name="MSRListInfo">
      <Column Name="ListID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ListName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiscGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InternID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Kperform" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscListID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSROverseaInfo" Member="MSROverseaInfos">
    <Type Name="MSROverseaInfo">
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisciplineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MonthID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverseaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentOverseaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSROverseaRequestInfo" Member="MSROverseaRequestInfos">
    <Type Name="MSROverseaRequestInfo">
      <Column Name="DisciplineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TrainingPrID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverseaReqID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRProblemSettingInfo" Member="MSRProblemSettingInfos">
    <Type Name="MSRProblemSettingInfo">
      <Column Name="ProblemSettingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TimeSlotPerMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeSlotName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRProgramDiscPrfInfo" Member="MSRProgramDiscPrfInfos">
    <Type Name="MSRProgramDiscPrfInfo">
      <Column Name="TrProgramID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisciplineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProgramDisciplineID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProgramDiscPrfID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRRegionInfo" Member="MSRRegionInfos">
    <Type Name="MSRRegionInfo">
      <Column Name="RegionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegionName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccomodationCap" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRStudentDiscPrfInfo" Member="MSRStudentDiscPrfInfos">
    <Type Name="MSRStudentDiscPrfInfo">
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisciplineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentDisciplineID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentDiscPrfID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRStudentFulfilledDiscInfo" Member="MSRStudentFulfilledDiscInfos">
    <Type Name="MSRStudentFulfilledDiscInfo">
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FulfilledID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisciplineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HospitalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrainingProgramID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentHistoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRStudentHospPrfInfo" Member="MSRStudentHospPrfInfos">
    <Type Name="MSRStudentHospPrfInfo">
      <Column Name="HospitalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentHospitalID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentHospPrfID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRStudentInfo" Member="MSRStudentInfos">
    <Type Name="MSRStudentInfo">
      <Column Name="StudentSQLID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentAveID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentAbID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentFulfilledID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentOverseaReqID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IfPrespective" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IfTransferBru" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DisciplinePrfID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HospitalPrfID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeightDiscPrf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeightHospPrf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeightWait" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeightChange" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisciplineListID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrainingProgramID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransferedRegionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRStudentRegionInfo" Member="MSRStudentRegionInfos">
    <Type Name="MSRStudentRegionInfo">
      <Column Name="RegionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransferedTo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StudentRegionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StReID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MSRTrainingProgramInfo" Member="MSRTrainingProgramInfos">
    <Type Name="MSRTrainingProgramInfo">
      <Column Name="TrainingProgramID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TrainingProgramName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TotalChange" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeightDiscPrf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CoefficientSumDes" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CoefficientMinDes" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CoefficientResCap" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CoefficientEmrCap" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CoefficientMinCap" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CoefficientUnusedAcco" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRWardDiscHospitalInfo" Member="MSRWardDiscHospitalInfos">
    <Type Name="MSRWardDiscHospitalInfo">
      <Column Name="DisciplineWardHospitalID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisciplineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WardID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HospitalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HospitalWardID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSRWardHospitalDemandInfo" Member="MSRWardHospitalDemandInfos">
    <Type Name="MSRWardHospitalDemandInfo">
      <Column Name="HospitalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HospitalName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HospitalWardID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinDemHospitalWardPeriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxDemHospitalWardPeriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResDemHospitalWardPeriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmrDemHospitalWardPeriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WardHospitalDemandPeriod" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaxDemHospitalWardYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinDemHospitalWardYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>